# This workflow will install Python dependencies and run testswith a single version of Python

name: pytest

on:
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: "3.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: run pytest
      run: |
        pytest -v
